[phases.setup]
nixPkgs = ["python311", "nodejs_20", "postgresql"]
nixLibs = []

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r requirements.txt",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "./start.sh"
